data_dir: C:/Users/jamie/projects/something
processed_dir: C:/Users/jamie/projects/something
output_dir: C:/Users/jamie/projects/something
model_dir: C:/Users/jamie/projects/something
sub_dir: C:/Users/jamie/projects/something
