data_dir: C:/Users/jamie/projects/kaggle-santa-2023-the-polytope-permutation-puzzle/data/
processed_dir: C:/Users/jamie/projects/kaggle-santa-2023-the-polytope-permutation-puzzle/processed_data/
output_dir: C:/Users/jamie/projects/kaggle-santa-2023-the-polytope-permutation-puzzle/output/
model_dir: C:/Users/jamie/projects/kaggle-santa-2023-the-polytope-permutation-puzzle/output/train/
sub_dir: C:/Users/jamie/projects/kaggle-santa-2023-the-polytope-permutation-puzzle/.
