defaults:
  - _self_
  - dir: local
  - data: data

data:
  puzzles_file: data/puzzles.csv
  puzzles_info_file: data/puzzle_info.csv
  submission_file: data/sample_submission.csv

config:
  specific_puzzle: 0
  generations: 2


