defaults:
  - _self_
  - dir: local
  - data: data

data:
  puzzles_file: data/puzzles.csv
  puzzles_info_file: data/puzzle_info.csv
  submission_file: submission.csv

config:
  puzzle_type:
  specific_puzzle:
  generations:
  init_moves: true


